QS/QS/Controllers/AdminController.cs
using System.Web.Mvc;

namespace QS.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Home()
        {
            return View();
        }


        public ActionResult QuotePrice()
        {
            return View();
        }

        public ActionResult AboutUs()
        {
            return View();
        }
    }
}

QS/QS/Controllers/BookingStatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QS.Models;

namespace QS.Controllers
{
    public class BookingStatesController : Controller
    {
        private QSDbContext db = new QSDbContext();
        [HttpGet]
        public ActionResult TracState()
        {
            return View(db.BookingStates.ToList());
        }
        [HttpPost]
        public ActionResult TracState(string SearchIdentifire)
        {
            return View(db.BookingStates.ToList().Where(x=>x.BookingIdentifire==SearchIdentifire).ToList());
        }
        // GET: BookingStates
        public ActionResult Index()
        {
            return View(db.BookingStates.ToList());
        }

        // GET: BookingStates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingState bookingState = db.BookingStates.Find(id);
            if (bookingState == null)
            {
                return HttpNotFound();
            }
            return View(bookingState);
        }

        // GET: BookingStates/Create
        public ActionResult Create()
        {
            BookingState bookingState = new BookingState();

            bookingState.BookingDateTime = DateTime.Now;

            return View(bookingState);
        }

        // POST: BookingStates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingStateId,BookingIdentifire,BookingDateTime,State")] BookingState bookingState)
        {
            if (ModelState.IsValid)
            {
                db.BookingStates.Add(bookingState);
                db.SaveChanges();
                Booking booking =  db.Bookings.Where(x => x.BookingIdentifire == bookingState.BookingIdentifire).FirstOrDefault();
                booking.BookingStatus = bookingState.State;
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Bookings");
               
             
            }

            return View(bookingState);
        }

        // GET: BookingStates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingState bookingState = db.BookingStates.Find(id);
            if (bookingState == null)
            {
                return HttpNotFound();
            }
            return View(bookingState);
        }

        // POST: BookingStates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingStateId,BookingIdentifire,BookingDateTime,State")] BookingState bookingState)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookingState).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookingState);
        }

        // GET: BookingStates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingState bookingState = db.BookingStates.Find(id);
            if (bookingState == null)
            {
                return HttpNotFound();
            }
            return View(bookingState);
        }

        // POST: BookingStates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookingState bookingState = db.BookingStates.Find(id);
            db.BookingStates.Remove(bookingState);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QS/QS/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QS.Models;

namespace QS.Controllers
{
    public class BookingsController : Controller
    {
        private QSDbContext db = new QSDbContext();

        // GET: Bookings
        public ActionResult Index()
        {
            return View(db.Bookings.ToList());
        }

        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            Booking booking = new Booking();
            Random random = new Random();
            booking.BookingIdentifire ="QS"+random.Next(1000000).ToString();
            booking.BookingStatus = "Panding";
            var SessionVaribale = Session["UserName"];
            if (SessionVaribale != null)
            {
                if (Session["UserName"].ToString() != "")
                {
                    booking.BookingUser = Session["UserName"].ToString();
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
           
            return View(booking);
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingId,BookingIdentifire,BookingPickupDate,BookingPickupTime,BookingParsalType,DelevaryName,DelevaryCountry,DelevaryCity,DelevaryAddress,BookingParsalWeight,BookingStatus,BookingUser")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                db.SaveChanges();
                BookingState state = new BookingState();
                state.BookingDateTime = DateTime.Now;     
                state.BookingIdentifire = booking.BookingIdentifire;
                state.State = booking.BookingStatus;
                db.BookingStates.Add(state);
                db.SaveChanges();
                ViewData["Booking"] = "Booking create Sucess";
            }

            return View(booking);
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            booking.BookingStatus = "Panding";
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

       
        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingId,BookingIdentifire,BookingPickupDate,BookingPickupTime,BookingParsalType,DelevaryName,DelevaryCountry,DelevaryCity,DelevaryAddress,BookingParsalWeight,BookingStatus")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QS/QS/Views/Shared/_Layout-Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-inverse {
            background-color: #168c81;
        }

        .navbar-nav li a {
            color: #fff !important;
        }

        .navbar-nav li a:hover {
                color: black !important;
         }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              
                <a href="@Url.Action("Index","Home")">
                    <img src="~/assets/images/Untithjled.png" id="main-logo" width="85" />
   
                </a>

                    @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"  style="margin-top:33px;" >
                    <li>@Html.ActionLink("Scheduled Pickup", "Create", "Bookings")</li>
                    <li>@Html.ActionLink("Tracking", "TracState", "BookingStates")</li>
                    <li>@Html.ActionLink("Update Booking Status", "Create", "BookingStates")</li>
                    <li>@Html.ActionLink("All Booking", "Index", "Bookings")</li>
                    <li>@Html.ActionLink("About Us", "AboutUs", "Admin")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right" style="margin-top:33px;">
                    <li>@Html.ActionLink("Login", "Login", "User")</li>
                    <li>@Html.ActionLink("SigunUp", "SignUp", "User")</li>
                    <li>@Html.ActionLink("QuotePrice", "QuotePrice", "Admin")</li>
                    <li>@TempData["User"]</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer">

            <div class="row">

                <div class="col-md-6">
                    <p class="pull-left">Copyright ©@DateTime.Now.Year . All rights reserved.</p>
                </div>
                <div class="col-md-6">

                    <div class="footer-links">

                        @Html.ActionLink("Sitemap", "Sitemap", "Home")
                    </div>




                </div>
            </div>


        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

QS/QS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<style>
    .navbar-inverse {
        background-color: #168c81;
    }
    .navbar-nav li a{
        color: #fff !important;
    }
    .navbar-nav li a:hover {
        color: black !important;
    }
</style>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")">
                    <img src="~/assets/images/Untithjled.png" id="main-logo" width="85" />
                  
                </a>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="margin-top:33px;">
                    <li>@Html.ActionLink("Scheduled Pickup", "Create", "Bookings")</li>
                    <li>@Html.ActionLink("Tracking", "TracState", "User")</li>
                    <li>@Html.ActionLink("My Tracking", "MyTrackingStates", "User")</li>
                    <li>@Html.ActionLink("About Us", "Contact", "Home")</li>
                  
                </ul>

                <ul class="nav navbar-nav navbar-right" style="margin-top:33px;">
                    <li>@Html.ActionLink("Login", "Login", "User")</li>
                    <li>@Html.ActionLink("Sign up", "SignUp", "User")</li>  
                    @*<li>@Html.ActionLink("Location", "Contact", "Home")</li>*@
                   
                    <li class="user-name">@TempData["User"]</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer class="footer">

            <div class="row">

                <div class="col-md-6">
                    <p class="pull-left">Copyright ©@DateTime.Now.Year . All rights reserved.</p>
                </div>
                <div class="col-md-6">

                    <div class="footer-links">

                        @Html.ActionLink("Sitemap", "Sitemap", "Home")
                    </div>

                
                 

                </div>
            </div>

            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

QS/QS/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-inverse {
            background-color: #168c81;
        }

        .navbar-nav li a {
            color: #fff !important;
        }

            .navbar-nav li a:hover {
                color: black !important;
            }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")">
                    <img src="~/assets/images/Untithjled.png" id="main-logo" width="85" style="margin-top:5px;" />
                    
                </a>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"  style="margin-top:33px;">

                    @*@*<li>@Html.ActionLink("Detals", "Contact", "Home")</li>
        <li>@Html.ActionLink("Payments", "Contact", "Home")</li>
        <li>@Html.ActionLink("About Us", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("About Us", "Contact", "Home")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right"  style="margin-top:33px;">
                    <li>@Html.ActionLink("Login", "Login", "User")</li>
                    <li>@Html.ActionLink("SigunUp", "SignUp", "User")</li>
                    <li>@Html.ActionLink("Location", "Contact", "Home")</li>
                    <li>@TempData["User"]</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer">

            <div class="row">

                <div class="col-md-6">
                    <p class="pull-left">Copyright ©@DateTime.Now.Year . All rights reserved.</p>
                </div>
                <div class="col-md-6">

                    <div class="footer-links">

                        @Html.ActionLink("Sitemap", "Sitemap", "Home")
                    </div>




                </div>
            </div>


        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>