QS/QS/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QS.Models;

namespace QS.Controllers
{
    public class BookingsController : Controller
    {
        private QSDbContext db = new QSDbContext();

        // GET: Bookings
        public ActionResult Index()
        {
            return View(db.Bookings.ToList());
        }

        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            Booking booking = new Booking();
            Random random = new Random();
            booking.BookingIdentifire ="QS"+random.Next(1000000).ToString();
            booking.BookingStatus = "Panding";
            var SessionVaribale = Session["UserName"];
            if (SessionVaribale != null)
            {
                if (Session["UserName"].ToString() != "")
                {
                    booking.BookingUser = Session["UserName"].ToString();
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
           
            return View(booking);
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingId,BookingIdentifire,BookingPickupDate,BookingPickupTime,BookingParsalType,DelevaryName,DelevaryCountry,DelevaryCity,DelevaryAddress,BookingParsalWeight,BookingStatus,BookingUser")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                db.SaveChanges();
                BookingState state = new BookingState();
                state.BookingDateTime = DateTime.Now;     
                state.BookingIdentifire = booking.BookingIdentifire;
                state.State = booking.BookingStatus;
                db.BookingStates.Add(state);
                db.SaveChanges();
                ViewData["Booking"] = "Booking create Sucess";
            }

            return View(booking);
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            booking.BookingStatus = "Panding";
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

       
        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingId,BookingIdentifire,BookingPickupDate,BookingPickupTime,BookingParsalType,DelevaryName,DelevaryCountry,DelevaryCity,DelevaryAddress,BookingParsalWeight,BookingStatus")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QS/QS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Location()
        {
        
            return View();
        }

        public ActionResult Sitemap()
        {

            return View();
        }
    }
}

QS/QS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

QS/QS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

QS/QS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="assets/images/Untitlhjhed.jpg" alt="Los Angeles">
        </div>

        <div class="item">
            <img src="assets/images/banner11_ef7b1646214d7e806023c3737c416902.jpg" alt="Chicago">
        </div>

        <div class="item">
            <img src="assets/images/Untitnnled.jpg" alt="New York">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

QS/QS/Views/Home/Location.cshtml
@{
    ViewBag.Title = "Location";
}

<h2>Location</h2>

QS/QS/Views/Home/Sitemap.cshtml
@{
    ViewBag.Title = "Sitemap";
}

<h2>Sitemap</h2>


<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Pages:</h3>
            <ul class="sitemap-items">
                <li><a href="@Url.Action("Index","Home")"><strong>Home</strong></a></li>
                <li><a href="@Url.Action("Contact","Home")"><strong>About</strong></a></li>
                <li><a href="@Url.Action("Create","Bookings")"><strong>Scheduled Pickup</strong></a></li>
                <li><a href="@Url.Action("TracState","User")"><strong>Tracking</strong></a></li>
             



            </ul>
        </div>
    </div>
</div>